export const CREATE_REQUISICAO = "CREATE_REQUISICAO";

export const RETRIEVE_REQUISICAOS = "RETRIEVE_REQUISICAOS";

export const UPDATE_REQUISICAO = "UPDATE_REQUISICAO";

export const DELETE_REQUISICAO = "DELETE_REQUISICAO";