export const CREATE_EQUIPAMENTO = "CREATE_EQUIPAMENTO";

export const RETRIEVE_EQUIPAMENTOS = "RETRIEVE_EQUIPAMENTOS";

export const UPDATE_EQUIPAMENTO = "UPDATE_EQUIPAMENTO";

export const DELETE_EQUIPAMENTO = "DELETE_EQUIPAMENTO";